name: CI

on:
  push:
    branches:
      - main

jobs:
  publishBenchRes:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-replica-set: test-rs
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.4
      - name: Download previous benchmark data
        uses: actions/cache@v1
        with:
         path: ./cache
         key: ${{ runner.os }}-benchmark
      - name: run benchmark test
        run: go test ./... -bench=. | tee output.txt
       # gh-pages branch is updated and pushed automatically with extracted benchmark data
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: My Project Go Benchmark
          tool: 'go'
          output-file-path: output.txt
          # Set auto-push to false since GitHub API token is not given
          auto-push: false
      # Push gh-pages branch by yourself
      - name: Push benchmark result
        run: git push 'https://ViktoriaValkova:${{ secrets.GITHUB_TOKEN }}@github.com/ViktoriaValkova/quant-internship-2023.git' gh-pages:gh-pages

