name: Go Test Coverage

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-replica-set: test-rs
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.4'
        
    - name: Install dependencies
      run: go get .
    
    - name: Build
      run: go build -v ./...

    - name: Generate Coverage Report
      run: go test -coverprofile=coverage.txt -covermode=atomic ./...
