name: Go Test Coverage

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.4'

      - name: Run Tests
        run: go test -v ./...

      - name: Generate Coverage Report
        run: go test -coverprofile=coverage.txt -covermode=atomic ./...
