name: misspell

on:
  - push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: sobolevn/misspell-fixer-action@master
    - name: Run misspell and show diffs
      run: |
            misspell -error -source=text -locale=en_US vendor > diff_output.txt
            cat diff_output.txt

    - uses: peter-evans/create-pull-request@v5 
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Fixes by misspell-fixer'
        title: 'Typos fix by misspell-fixer'
