name: reviewdog

on: push

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Review code
      uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest

    - name: Run reviewdog
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: reviewdog -reporter=github-check -runners=golint,govet,misspell
