name: reviewdog

on:
  push:

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Review code
      uses: reviewdog/action-setup@v2
      with:
        reviewdog_version: latest
    - run: reviewdog -reporter=github-check -runners=golint,govet
